### ISSUE TITLE
Generate audio podcast feeds.

### ISSUE THREAD

**Issue by ypid** [cccc/media-webgen#3]
Hi

Not sure if I am the first one how suggests such a feature … It should be not to hard to support audio only feeds as well? Any thoughts?

**Comment by manno** [comment]
Hi,

You're probably looking for https://github.com/voc/media-frontend

However media.ccc.de already supports audio-only feeds, they are listed in the HTML header. For example: https://media.ccc.de/browse/conferences/chaoscologne/1c2/podcast-mp3.xml

**Comment by ypid** [comment]
Thanks. I was just looking at the start page for feeds.

What about https://media.ccc.de/podcast-mp3.xml? Should I open a issue at https://github.com/voc/media-frontend for that?

**Comment by manno** [comment]
Sure open an issue so we don't forget about this. I'm especially interested what content you'd expect from a feed on the start page: all (3000?) audio filess , audio from all conferences of the last year, the last 500 audio files....?

However it's unlikely that these feeds will happen before 'the big rewrite'.
